sudo: false
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby-9.1.6.0
  #- rbx-2 for some reason it doesn't work in travis. also other people has problems with it, try in a month again
before_install: gem install bundler -v 1.13.6
