sudo: false
language: ruby
addons:
  mariadb: '10.0'
rvm:
  - 2.4.6
  - 2.5.4
  - 2.6.3
before_install: gem install bundler -v 1.17.2
cache: bundler
matrix:
  include:
     - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true