sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.1.6.0
before_install: gem install bundler -v 1.13.7
cache: bundler
matrix:
  include:
     - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true