class RequestDummyLog
  attr_accessor :application_server_request_start, :application_server_request_end, :data, :uid, :status_code

  def save
    true
  end
end

RSpec.shared_context 'spec_data' do
  let(:rack_headers) do
    {
      "rack.version" => [1, 3],
      "rack.input" => StringIO.new('foo'),
      "rack.errors" => StringIO.new('bar'),
      "rack.multithread" => true,
      "rack.multiprocess" => true,
      "rack.run_once" => false,
      "rack.test" => true,
      "rack.url_scheme" => "http",
      "REQUEST_METHOD" => "GET",
      "SERVER_NAME" => "example.org",
      "SERVER_PORT" => "80",
      "QUERY_STRING" => "",
      "PATH_INFO" => "/",
      "HTTPS" => "off",
      "SCRIPT_NAME" => "",
      "CONTENT_LENGTH" => "0",
      "REMOTE_ADDR" => "127.0.0.1",
      "HTTP_HOST" => "example.org",
      "HTTP_COOKIE" => ""
    }
  end

  let(:rails_headers) do
    {
      "rack.version" => [1, 6],
      "rack.errors" => StringIO.new("#<IO:<STDERR>>"),
      "rack.multithread" => true,
      "rack.multiprocess" => false,
      "rack.run_once" => false,
      "rack.url_scheme" => "http",
      "SCRIPT_NAME" => "",
      "QUERY_STRING" => "",
      "SERVER_SOFTWARE" => "puma 6.4.2 The Eagle of Durango",
      "GATEWAY_INTERFACE" => "CGI/1.2",
      "REQUEST_METHOD" => "GET",
      "REQUEST_PATH" => "/",
      "REQUEST_URI" => "/foo",
      "SERVER_PROTOCOL" => "HTTP/1.1",
      "HTTP_HOST" => "localhost:4000",
      "HTTP_USER_AGENT" => "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
      "HTTP_ACCEPT" => "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
      "HTTP_ACCEPT_LANGUAGE" => "sk,cs;q=0.8,en-US;q=0.5,en;q=0.3",
      "HTTP_ACCEPT_ENCODING" => "gzip, deflate, br",
      "HTTP_CONNECTION" => "keep-alive",
      "HTTP_UPGRADE_INSECURE_REQUESTS" => "1",
      "HTTP_SEC_FETCH_DEST" => "document",
      "HTTP_SEC_FETCH_MODE" => "navigate",
      "HTTP_SEC_FETCH_SITE" => "cross-site",
      "puma.request_body_wait" => 0.004490002989768982,
      "SERVER_NAME" => "localhost",
      "SERVER_PORT" => "4000",
      "PATH_INFO" => "/foo",
      "REMOTE_ADDR" => "::1",
      "HTTP_VERSION" => "HTTP/1.1",
      "puma.socket" => StringIO.new("#<TCPSocket:fd 13, AF_INET, 127.0.0.1, 4000>"),
      "rack.hijack?" => true,
      "rack.hijack" => StringIO.new("#<Puma::Client:0xa244 @ready=true>"),
      "rack.input" => StringIO.new("#<Puma::NullIO:0x00007f2ab670c4b0>"),
      "rack.after_reply" => [],
      "puma.config" => StringIO.new("#<Puma::Configuration:0x00007f2ab6736cd8>"),
      "action_dispatch.parameter_filter" => [/(?i:passw)|(?i:email)|(?i:secret)|(?i:token)|(?i:_key)|(?i:crypt)|(?i:salt)|(?i:certificate)|(?i:otp)|(?i:ssn)/],
      "action_dispatch.redirect_filter" => [],
      "action_dispatch.secret_key_base" => "1aa711780ed3d17cc49e499266c013016a9fb209184dfe1740f12066018fb157e17c8a3dbc8caf2d06121f2ec32c3fae5d1e44e168c79340000688ee6f9a993a",
      "action_dispatch.show_exceptions" => :all,
      "action_dispatch.show_detailed_exceptions" => true,
      "action_dispatch.log_rescued_responses" => true,
      "action_dispatch.debug_exception_log_level" => 3,
      "action_dispatch.logger" => StringIO.new("#<ActiveSupport::BroadcastLogger:0x00007f2ab6f0a298>"),
      "action_dispatch.backtrace_cleaner" => StringIO.new("#<Rails::BacktraceCleaner:0x00007f2ab66cebd8>"),
      "action_dispatch.key_generator" => StringIO.new("#<ActiveSupport::CachingKeyGenerator:0x00007f2ab6827340>"),
      "action_dispatch.http_auth_salt" => "http authentication",
      "action_dispatch.signed_cookie_salt" => "signed cookie",
      "action_dispatch.encrypted_cookie_salt" => "encrypted cookie",
      "action_dispatch.encrypted_signed_cookie_salt" => "signed encrypted cookie",
      "action_dispatch.authenticated_encrypted_cookie_salt" => "authenticated encrypted cookie",
      "action_dispatch.use_authenticated_cookie_encryption" => true,
      "action_dispatch.encrypted_cookie_cipher" => nil,
      "action_dispatch.signed_cookie_digest" => nil,
      "action_dispatch.cookies_serializer" => :json,
      "action_dispatch.cookies_digest" => nil,
      "action_dispatch.cookies_rotations" => StringIO.new("#<ActiveSupport::Messages::RotationConfiguration:0x00007f2ab718a1f8>"),
      "action_dispatch.cookies_same_site_protection" => StringIO.new("#<Proc:0x00007f2ab66ce070 /home/damon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/application.rb:641>"),
      "action_dispatch.use_cookies_with_metadata" => true,
      "action_dispatch.content_security_policy" => nil,
      "action_dispatch.content_security_policy_report_only" => false,
      "action_dispatch.content_security_policy_nonce_generator" => nil,
      "action_dispatch.content_security_policy_nonce_directives" => nil,
      "action_dispatch.permissions_policy" => nil,
      "action_dispatch.routes" => StringIO.new("#<ActionDispatch::Routing::RouteSet:0x00007f2ab6ba3988>"),
      "ROUTES_11240_SCRIPT_NAME" => "",
      "ORIGINAL_FULLPATH" => "/foo",
      "ORIGINAL_SCRIPT_NAME" => "",
      "action_dispatch.authorized_host" => "localhost",
      "action_dispatch.request_id" => "6e4ec1cd-7501-4a82-a429-bee89d75a437",
      "action_dispatch.remote_ip" => StringIO.new("#<ActionDispatch::RemoteIp::GetIp:0x00007f2ab6638d40>"),
      "rails.rack_logger_tag_count" => 0,
      "rack.session" => StringIO.new("#<ActionDispatch::Request::Session:0x144d8 not yet loaded>"),
      "rack.session.options" => StringIO.new("#<ActionDispatch::Request::Session::Options:0x00007f2ab47a8da8>"),
      "rack.tempfiles" => [],
      "action_dispatch.request.path_parameters" => {:controller=>"posts", :action=>"index"},
      "action_dispatch.route_uri_pattern" => "/",
      "action_controller.instance" => StringIO.new("#<PostsController:0x00000000014500>"),
      "action_dispatch.request.content_type" => nil,
      "rack.request.form_input" => StringIO.new("#<Puma::NullIO:0x00007f2ab670c4b0>"),
      "rack.request.form_hash" => {},
      "action_dispatch.request.request_parameters" => {},
      "rack.request.query_string" => "",
      "rack.request.query_hash" => {},
      "action_dispatch.request.query_parameters" => {},
      "action_dispatch.request.parameters" => {"controller"=>"posts", "action"=>"index"},
      "action_dispatch.request.formats" => [StringIO.new("#<Mime::Type:0x00007f2ab692f0a8>")]
    }
  end
end
